# Generated by Django 5.0.1 on 2024-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_reg',
            fields=[
                ('phno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=20)),
                ('h_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hostels',
            fields=[
                ('h_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('price4', models.IntegerField()),
                ('price6', models.IntegerField()),
                ('price8', models.IntegerField()),
                ('price10', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=400)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('share4', models.IntegerField()),
                ('share6', models.IntegerField()),
                ('share8', models.IntegerField()),
                ('share10', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('phno', models.IntegerField()),
                ('img', models.FileField(null=True, upload_to='')),
                ('gmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User_registration',
            fields=[
                ('phno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=20)),
                ('ck_in', models.DateField(blank=True, null=True)),
                ('ck_out', models.DateField(blank=True, null=True)),
                ('price_paid', models.IntegerField(blank=True, null=True)),
                ('sharing', models.CharField(blank=True, max_length=10, null=True)),
                ('h_id', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
